### ISSUE TITLE
unknown-service-name

### ISSUE THREAD

**Issue by eugene-chernyshenko** [MetinSeylan/Nestjs-OpenTelemetry#24]
How to specify service name?

**Comment by MetinSeylan** [comment]
depends on your exporter configuration, for example in zipkinexporter you can use serviceName prop

**Comment by niallthomson** [comment]
I've just stumbled across this and I think there perhaps be an issue here after all. Or my configuration is wrong :D

The other languages I've instrumented with OpenTelemetry libraries have respected the `OTEL_SERVICE_NAME` environment variable out of the box whereas in this case I'm getting `UNKNOWN` as the service name, probably because its being overwritten by the default value in `OpenTelemetryModuleDefaultConfig`.  I tried enabling the `EnvDetector` but I don't see any of the expected resource attributes getting set. I also don't see any resource attributes from the `Ec2Detector` despite running on EC2.
