### ISSUE TITLE
Question: How to use custom instrumentations

### ISSUE THREAD

**Issue by iddan** [MetinSeylan/Nestjs-OpenTelemetry#43]
How can I use custom instrumentations with this library? I looked in the code for `registerInstrumentations` but couldn't find any example.

**Comment by Maklestiguan** [comment]
Basically you should provide it in module config, since it [extends](https://github.com/MetinSeylan/Nestjs-OpenTelemetry/blob/main/src/OpenTelemetryModuleConfig.ts#L28) `Partial<NodeSDKConfiguration>`, then [merges](https://github.com/MetinSeylan/Nestjs-OpenTelemetry/blob/main/src/OpenTelemetryModule.ts#L34) default config and what you have provided (defaults get overridden) and then `nodeSDK` [goes with your config as constructor args](https://github.com/MetinSeylan/Nestjs-OpenTelemetry/blob/main/src/OpenTelemetryModule.ts#L72)

**Comment by iddan** [comment]
Thanks! Maybe better add it to the main readme?

**Comment by MetinSeylan** [comment]
#49

**Comment by iddan** [comment]
Thank you!
